version: '3.8'
services:
  phela_app:
    build: .
    image: latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      # Database Configuration
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=phela
      - DB_USERNAME=your_mysql_user
      - DB_PASSWORD=your_mysql_password

      # JWT Configuration
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}

      # Application Configuration
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}

      # Email Configuration
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      # Cloudinary Configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

      # File Upload Configuration
      - FILE_UPLOAD_DIR=${FILE_UPLOAD_DIR:-uploads}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10MB}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10MB}

      # VNPay Configuration
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=${VNPAY_URL:-https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}

      # Hibernate Configuration
      - JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO:-update}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL:-false}